# Used to test Ubuntu/Linux builds

FROM ubuntu:22.04

# Install clang and cmake
RUN apt-get update && apt-get install -y \
    build-essential clang cmake git \
    openssl libssl-dev \
    libx11-dev xorg-dev

# Copy the project files
COPY . /cas/

# Set the working directory
WORKDIR /cas

# Build the project
RUN chmod +x build.sh
RUN ./build.sh

# Run the project
CMD ["./build-debug/ComputerAlgebraSystem"]